### ISSUE TITLE
[Feature] Name of document in Menu Bar

### ISSUE THREAD

**Issue by juanhidalgo** [alexkim205/G-Desktop-Suite#57] opened 2020-05-20 14:24 UTC
When you have many open documents and right click on the menu bar they are all called "Google Drive". It would be nice if the name of the document appeared there so it would be easier to switch between docs

**Comment by mding5692** [comment] 2020-05-20 16:29
Think this is a duplicate of #44

**Closed** 2020-05-20 20:39 UTC
Labels: duplicate
